# Generated by Django 3.2.7 on 2021-09-13 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('poster', models.CharField(max_length=200)),
                ('adult', models.BooleanField()),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('original_title', models.CharField(max_length=200)),
                ('original_language', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('popularity', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movietut.genre')),
            ],
        ),
    ]
