# Generated by Django 3.2.7 on 2021-09-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('name_fr', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Production_Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('logo', models.CharField(default='', max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('origin_country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Production_Country',
            fields=[
                ('iso', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spoken_Languages',
            fields=[
                ('iso', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imdb_id', models.CharField(default='', max_length=10)),
                ('poster', models.CharField(default='', max_length=200)),
                ('adult', models.BooleanField()),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('original_title', models.CharField(max_length=200)),
                ('original_language', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('popularity', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.FloatField()),
                ('budget', models.IntegerField(default=0)),
                ('revenue', models.IntegerField(default=0)),
                ('runtime', models.IntegerField(default=0)),
                ('status', models.CharField(default='', max_length=200)),
                ('tagline', models.CharField(default='', max_length=200)),
                ('genres', models.ManyToManyField(to='movietut.Genre')),
                ('production_companies', models.ManyToManyField(to='movietut.Production_Company')),
                ('production_countries', models.ManyToManyField(to='movietut.Production_Country')),
                ('spoken_languages', models.ManyToManyField(to='movietut.Spoken_Languages')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
