# Generated by Django 3.2.7 on 2021-09-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tagline',
            field=models.TextField(default=''),
        ),
    ]
