# Generated by Django 3.2.7 on 2021-09-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietut', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='name_fr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
