# Generated by Django 3.2.7 on 2021-09-13 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movietut', '0003_auto_20210913_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
