# Generated by Django 3.2.7 on 2021-10-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietut', '0003_alter_movie_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.BigIntegerField(default=0),
        ),
    ]
