# Generated by Django 3.2.7 on 2021-09-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietut', '0005_alter_movie_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production_Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('logo', models.CharField(default=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('origin_country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Production_Country',
            fields=[
                ('iso', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Spoken_Languages',
            fields=[
                ('iso', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release_date']},
        ),
        migrations.AddField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='movie',
            name='revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='tagline',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_companies',
            field=models.ManyToManyField(to='movietut.Production_Company'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_countries',
            field=models.ManyToManyField(to='movietut.Production_Country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='spoken_languages',
            field=models.ManyToManyField(to='movietut.Spoken_Languages'),
        ),
    ]
