# Generated by Django 3.2.7 on 2021-09-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movietut', '0006_auto_20210916_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('login', models.CharField(default='', max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=25)),
                ('email', models.CharField(default='', max_length=50)),
                ('first_name', models.CharField(default='', max_length=15)),
                ('last_name', models.CharField(default='', max_length=25)),
                ('movies', models.ManyToManyField(to='movietut.Movie')),
            ],
        ),
    ]
